export const mastersKeys = [
  "Bill of Lading Number",
  "Freight Terms",
  "Export References",
  "Shipper Name",
  "Shipper Address",
  "Shipper Contact Info",
  "Consignee Name",
  "Consignee Address",
  "Consignee Contact Info",
  "Notify Party Name",
  "Notify Party Address",
  "Notify Party Contact Info",
  "Shipper’s Declaration of Value",
  "Express Release",
  "AES ITN",
  "HS Code",
  "Comments",
];
