export const masters3Fields = {
  " 2. EXPORTER":
    "JOHN WICK SALE LLC 450 POTTER STREET UNIT Q, Tel: 4569874008, BLUESBORO, NC 12505. UNITED STATES",
  " ZIP CODE": "",
  " 3. CONSIGNED TO":
    "HASSAN RASHED MUHIEDDINE MANTRA AZIZ TOBI BLDG 7TH FL, Tel:7894123418277,BEIRUT. LEBANON",
  " 4. NOTIFY PARTY /INTERMEDIATE CONSIGNEE (Name and address)": "",
  " 5. DOCUMENT NUMBER": "GCVDS1OWLM2240",
  " 6. EXPORT REFERENCES": "",
  " 7. FORWARDING AGENT (Name and address -references)": "DWI Services LLC",
  " 8. POINT (STATE) OF ORIGIN OR FTZ NUMBER": "",
  " 9. DOMESTIC ROUT ING/EXPORT INSTRUCTIONS": "",
  " 10. LOADING PIER /TERMINAL": "",
  " 11 TYPE OF MOVE": "Barge",
  " 11a CONTAINERIZED (Vessel only)": "Yes No",
  " 12. PRE-CARRIAGE BY": "",
  " 13 PLACE OF RECEPT BY PRE -CARRIER": "",
  " 14. EXPORTNG CARRIER": "Death Star / 10",
  " 15 PORT OF LOADING /EXPORT": "Wilmington",
  " 16. FOREIGN PORT OF UNLOADNG (Vessel and air only)": "Beirut",
  " 17 PLACE OF DELMERY BY ON -CARRIER": "",
  " MARKS AND NUMBERS (18)": "",
  " NUMBER OF PACKAGES (19)": "1 VEH",
  " DESCRIPTION OF COMMODITIES (20)":
    "2025 JEEP GRAND CHEROKEE LAREDO VIN:4R3WJFAG8CC291235 AES ITN:T12960925054288 prepaid/telex release",
  " GROSS WEIGHT (Kilos) (21)": "2,113.74 Kg",
  " MEASUREMENT (22)": "16.47 m3",
};

export const masters3FieldsArr = [
  {
    " 2. EXPORTER":
      "JOHN WICK SALE LLC 450 POTTER STREET UNIT Q, Tel: 4569874008, BLUESBORO, NC 12505. UNITED STATES",
  },
  { " ZIP CODE": "" },
  {
    " 3. CONSIGNED TO":
      "HASSAN RASHED MUHIEDDINE MANTRA AZIZ TOBI BLDG 7TH FL, Tel:7894123418277,BEIRUT. LEBANON",
  },
  { " 4. NOTIFY PARTY /INTERMEDIATE CONSIGNEE (Name and address)": "" },
  { " 5. DOCUMENT NUMBER": "GCVDS1OWLM2240" },
  { " 6. EXPORT REFERENCES": "" },
  { " 7. FORWARDING AGENT (Name and address -references)": "DWI Services LLC" },
  { " 8. POINT (STATE) OF ORIGIN OR FTZ NUMBER": "" },
  { " 9. DOMESTIC ROUT ING/EXPORT INSTRUCTIONS": "" },
  { " 10. LOADING PIER /TERMINAL": "" },
  { " 11 TYPE OF MOVE": "Barge" },
  { " 11a CONTAINERIZED (Vessel only)": "Yes No" },
  { " 12. PRE-CARRIAGE BY": "" },
  { " 13 PLACE OF RECEPT BY PRE -CARRIER": "" },
  { " 14. EXPORTNG CARRIER": "Death Star / 10" },
  { " 15 PORT OF LOADING /EXPORT": "Wilmington" },
  { " 16. FOREIGN PORT OF UNLOADNG (Vessel and air only)": "Beirut" },
  { " 17 PLACE OF DELMERY BY ON -CARRIER": "" },
  { " MARKS AND NUMBERS (18)": "" },
  { " NUMBER OF PACKAGES (19)": "1 VEH" },
  {
    " DESCRIPTION OF COMMODITIES (20)":
      "2025 JEEP GRAND CHEROKEE LAREDO VIN:4R3WJFAG8CC291235 AES ITN:T12960925054288 prepaid/telex release",
  },
  { " GROSS WEIGHT (Kilos) (21)": "2,113.74 Kg" },
  { " MEASUREMENT (22)": "16.47 m3" },
];
